export const ACTION = 'action'
export const ACTIONS = 'actions'
export const BENCHMARK = 'benchmark'
export const BENCHMARKS = 'benchmarks'
export const CONDITION = 'condition'
export const CONDITIONS = 'conditions'