export const EXPAND_SIDEBAR = 'EXPAND_SIDEBAR'
export const COLLAPSE_SIDEBAR = 'COLLAPSE_SIDEBAR'

export const OPEN_VIDEO_MODAL = 'OPEN_VIDEO_MODAL'
export const CLOSE_VIDEO_MODAL = 'CLOSE_VIDEO_MODAL'

export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST'
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS'
export const FETCH_MORE_CONTACTS_SUCCESS = 'FETCH_MORE_CONTACTS_SUCCESS'
export const FETCH_CONTACTS_FAILED = 'FETCH_CONTACTS_FAILED'
export const CHANGE_QUERY = 'CHANGE_QUERY'
export const CLEAR_ITEMS = 'CLEAR_ITEMS'

export const DELETE_CONTACTS = 'DELETE_CONTACTS'
export const FILTER_CONTACTS = 'FILTER_CONTACTS'

export const ADD_CONTACT = 'ADD_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'
export const EDIT_CONTACT = 'EDIT_CONTACT'
export const FETCH_CONTACT = 'FETCH_CONTACT'
