export const EXPAND_SIDEBAR = 'EXPAND_SIDEBAR'
export const COLLAPSE_SIDEBAR = 'COLLAPSE_SIDEBAR'

export const OPEN_VIDEO_MODAL = 'OPEN_VIDEO_MODAL'
export const CLOSE_VIDEO_MODAL = 'CLOSE_VIDEO_MODAL'

export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST'
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS'
export const FETCH_MORE_CONTACTS_SUCCESS = 'FETCH_MORE_CONTACTS_SUCCESS'
export const FETCH_CONTACTS_FAILED = 'FETCH_CONTACTS_FAILED'

export const SHOW_CONTACT_FILTERS = 'SHOW_CONTACT_FILTERS'

export const DESELECT_ALL_ITEMS = 'DESELECT_ALL_ITEMS';
export const SELECT_ALL_ITEMS = 'SELECT_ALL_ITEMS';
export const DESELECT_SOME_ITEMS = 'DESELECT_SOME_ITEMS';
export const SELECT_SOME_ITEMS = 'SELECT_SOME_ITEMS';
export const DESELECT_ITEM = 'DESELECT_ITEM';
export const SELECT_ITEM = 'SELECT_ITEM';
export const SHIFT_KEY_DOWN = 'SHIFT_KEY_DOWN';
export const SHIFT_KEY_UP = 'SHIFT_KEY_UP';

export const CHANGE_CONTEXT = 'CHANGE_CONTEXT'
export const CHANGE_QUERY = 'CHANGE_QUERY'
export const CLEAR_ITEMS = 'CLEAR_ITEMS'
export const CLEAR_STATE = 'CLEAR_STATE'

export const DELETE_CONTACTS = 'DELETE_CONTACTS'
export const FILTER_CONTACTS = 'FILTER_CONTACTS'

export const ADD_CONTACT = 'ADD_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'
export const EDIT_CONTACT = 'EDIT_CONTACT'
export const FETCH_CONTACT = 'FETCH_CONTACT'

export const BULK_JOB_FINISHED = 'BULK_JOB_FINISHED'
export const BULK_JOB_PROCESSED_ITEMS = 'BULK_JOB_PROCESS_ITEMS'
export const BULK_JOB_ERROR = 'BULK_JOB_ERROR'
export const BULK_JOB_INIT = 'BULK_JOB_INIT'


/**
 *  Reports actions
 */

export const FETCH_REPORT_NAVBAR = 'FETCH_REPORT_NAVBAR';
export const SELECTED_REPORT_NAVBAR_CHANGE = 'SELECTED_REPORT_NAVBAR_CHANGE';
export const FETCH_REPORTS_IN_PAGE = 'FETCH_REPORTS_IN_PAGE';

export const FETCH_REPORT = 'FETCH_REPORT';

export const REPORT_DATE_CHANGE = 'REPORT_DATE_CHANGE';
export const REPORT_DROPDOWN_CHANGE  = 'REPORT_DROPDOWN_CHANGE';


