<?php

namespace Groundhogg\Reporting\New_Reports;

use Groundhogg\Classes\Activity;
use Groundhogg\Contact_Query;
use Groundhogg\Event;
use Groundhogg\Funnel;
use function Groundhogg\get_db;
use function Groundhogg\get_request_var;
use function Groundhogg\isset_not_empty;

class Chart_Draw extends Base_Line_Chart_Report {
	public function get_datasets() {
		// TODO: Implement get_datasets() method.
	}

	public function get_options() {
		return parent::get_options(); // TODO: Change the autogenerated stub
	}



	public function get_line_style() {
		return parent::get_line_style(); // TODO: Change the autogenerated stub
	}



}
