name: WP.org Deploy + Zip on Any Tag

on:
  push:
    tags:
      - "*"   # every tag

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SLUG: groundhogg  # change if your plugin folder differs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Work out what kind of tag this is
      - name: Determine release type
        id: meta
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME}"

          # Real release: digits and dots only (any length, e.g., 4.1 or 4.1.2.5.6)
          if [[ "$TAG" =~ ^[0-9]+(\.[0-9]+)*$ ]]; then
            echo "is_real=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_real=false" >> "$GITHUB_OUTPUT"
          fi

          # Pre-release: contains ".rc"
          if [[ "$TAG" == *".rc"* ]]; then
            echo "is_rc=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_rc=false" >> "$GITHUB_OUTPUT"
          fi

      # Always build a ZIP. Only deploy to SVN when it's a real release.
      - name: Build ZIP (and deploy if real release)
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
          dry-run: ${{ steps.meta.outputs.is_real != 'true' }}  # true for rc/dev, false for real
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: ${{ env.SLUG }}

      # Create Release for real and .rc tags (mark rc as prerelease); attach the generated ZIP
      - name: Create GitHub Release + upload ZIP
        if: ${{ steps.meta.outputs.is_real == 'true' || steps.meta.outputs.is_rc == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: ${{ steps.meta.outputs.is_rc == 'true' }}
          files: ${{ steps.deploy.outputs.zip-path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # For dev-ish tags (alpha/dev/anything else), save the ZIP as a workflow artifact
      - name: Upload ZIP as workflow artifact
        if: ${{ steps.meta.outputs.is_real != 'true' && steps.meta.outputs.is_rc != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}-zip
          path: ${{ steps.deploy.outputs.zip-path }}
